=== labra/RailDataForum_ValidationWorkshop/examples/person.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 <xsd:element name="Person" type="Person"/>
 
 <xsd:complexType name="Person">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>
      <xsd:element name="birthPlace" type="Place" minOccurs="0" />
      <xsd:element name="birthDate"  type="xsd:date" minOccurs="0" />
      <xsd:element name="employer"   type="Organization" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="knows"      type="Person" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

 <xsd:complexType name="Place">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>
      <xsd:element name="country" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

 <xsd:complexType name="Organization">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== labra/RailDataForum_ValidationWorkshop/examples/person.xml
<?xml version="1.0"?>
<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xsi:schemaLocation="http://www.w3.org/2001/XMLSchema person.xsd">
 <name>Tim Berners-Lee</name>
 <birthPlace>
   <name>London</name>
   <country>UK</country>
 </birthPlace>
 <birthDate>1955-06-08</birthDate>
 <employer>
   <name>CERN</name>
 </employer>
 <knows>
  <name>Jose</name>
  <birthPlace>
    <name>Oviedo</name>
    <country>Spain</country>
   </birthPlace> 
  </knows>
</Person>
